### ISSUE TITLE
REQ: Change form IDs to character-server internally

### ISSUE THREAD

**Issue by speaker** [kahluamods/konfersk#10]
When I look at the data storage in SavedVariables it appears that every character gets a unique ID assigned that's use for lookup. If I'm wrong, please ignore the rest of this. 

There is no technical reason to do this in LUA and WoW addons. Everything is hashed already, and using a lookup code is literally just doubling the number of hash calls internally. Further, every PlayerName-ServerName is guaranteed unique anyhow so the ID is just adding a layer of complexity that makes syncing substantially more difficult. The change not only would remove a whole host of syncing issues, it would also make the Saved Variables much simpler and human readable.

**Comment by jkj** [comment]
The thing you are missing about the data model is that if someone has a 12-character name, every time it is needed it takes 12 characters. Using an ID as I do requires 4 - always, no matter what you rename your character to. There are other reasons too - like for example how compactly I can represent an entire raid. The data model is not going to change it was designed this way for a reason.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by jkj** [comment]
Also btw - changing ID's would not *remove* any syncing issues - it would cause them. The syncing issues are 100% related to blizzard silently throttling messages. If I was to use full name-server pairs - asside from the ambiguity (and it IS ambiguous despite that you think) it would cause the size of the payload to significantly INCREASE not decrease - so it would make syncing even more fragile. The savedvariables file is NOT intended for human consumption. and I am not going to break a good design to accomodate THAT. So no, this is not going to change.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by speaker** [comment]
If 2 admins add the same character and they are assigned different IDs (as has happened to us) it send the data into a tail spin that thus far has required a wipe and rebuild for all but one member. The addon(s) I wrote tracked characters, alternates, and servers, and I never had an issue using the name as unique on any given server. (I seem to remember the name being guaranteed unique on a server in the API, but it's been a while.)

In any case, asked and answered, thank you.

**Comment by jkj** [comment]
That is an *exceptionally* rare case and usually only happens when a guild is highly fractured (i.e two admins are in the same guild but essentially running as if it is two guilds). It is also extremely easy to fix - just delete one of the duplicate names. The IDs will not be duplicated because each admin has their own prefix (the owner is 0, the first admin is 1, the second is 2 etc) so it is impossible for the same ID to be used,, but you can end up with the same player name with different IDs. When that happens simply delete the duplicates till there is only 1 left and ensure you are all synced together. Not sure how the data gets into a "tail spin" - you can simply adjust the position if there has been erroneous movement of one of the characters. Please can you expand on that further as that might indeed indicate a bug somewhere if there was other data corruption (which there shouldnt be because its using the unique ID notthe character name).

Also please remember the ID thing is *NOT* to simply guarantee uniqueness. That is not the reason I use it - it is for data size reduction. I only need to store the name once, as opposed to every time I need the name (each list the person is on, each time they are awarded loot, each time they are moved due to other people suiciding etc) - and the ID is *constant length* as opposed to variable length. That means it takes exactly 100 characters to fully represent a 25-man raid. If you use the server-disambiguated name, which will be a "Name-server" pair it can be up to 600 characters to represent the same thing. Thats a 6-fold increase in data that is produced often. That is bad. Also your concern about speed is completely unwarranted - the table lookup is so damned close to instantaneous as makes no difference. Has the speed of the mod *EVER* been a problem?

Also you didn't answer my previous question as to whether or not you are still getting sync errors or messages about fake messages after r17 which now uses libdeflate to compress the sync payload? We're over 3000 downloads in and not a single complaint so I do think it is as fixed as it is possible to get but I'd like to hear your experience.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by speaker** [comment]
As a follow up, we never got error messages, It just failed to work. Rolls getting ignored, Bids getting ignored, Manual movement in the list would fail to update other admins. No messages, just unexpected results.

**Comment by jkj** [comment]
I really am sorry to hear you had such a bad experience. The mod used to be almost flawless before Blizzard moved the ground under my feet. The next version (r18) will have even more data compressed. There is now almost nothing more I can do to reduce the payload size which is what is causing all the trouble. And that was only started when they lowered the tripwire significantly in Classic Wow 1.13.2 and changed the API so that it would just silently drop what it considered "excess" messages on the floor, so I couldn't possibly debug stuff because I never ever got the messages. This is a genuine bug in the wow client and it has been reported by many people not just me.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
